services:
  db:
    image: postgres:16.2-alpine
    restart: always
    command: postgres -c wal_level=logical # Required by Zero
    environment:
      - POSTGRES_DB=liquachat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-54783}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d liquachat"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - SKIP_ENV_VALIDATION=true
      - ZERO_UPSTREAM_DB=postgresql://postgres:${DB_PASSWORD}@db:5432/liquachat?sslmode=disable
    command: sh -c "pnpm run db:push"
    depends_on:
      db:
        condition: service_healthy

  zero:
    image: rocicorp/zero@sha256:4ea7e59252b586d8b42ca3f59b5fbfdebf7e33ffc9b4fc048036a78c0612cb10
    restart: always
    environment:
      - ZERO_UPSTREAM_DB=postgresql://postgres:${DB_PASSWORD}@db:5432/liquachat?sslmode=disable
      - ZERO_REPLICA_FILE=/data/sync-replica.db
      - ZERO_AUTH_JWKS_URL=http://nginx/api/auth/jwks
      - ZERO_PUSH_URL=http://nginx/api/zero/push
    volumes:
      - zero_data:/data
    depends_on:
      migrator:
        condition: service_completed_successfully

  zero-permissions-deployer:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - ZERO_UPSTREAM_DB=postgresql://postgres:${DB_PASSWORD}@db:5432/liquachat?sslmode=disable
    command: npx zero-deploy-permissions -p ./src/zero/schema.ts
    depends_on:
      zero:
        condition: service_started

  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: sh -c "ollama run deepseek-r1:8b"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:11434/ | grep 'Ollama is running' || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # client-side env vars
        # we need to separate them from the server-side env vars because they are built into the bundle
        - NEXT_PUBLIC_ZERO_SERVER_URL=http://localhost:${APP_PORT:-54782}/proxy-zero
        - NEXT_PUBLIC_NODE_ENV=production
    restart: always
    environment:
      # server-side env vars
      - NODE_ENV=production
      - ZERO_UPSTREAM_DB=postgresql://postgres:${DB_PASSWORD}@db:5432/liquachat?sslmode=disable
      - ZERO_REPLICA_FILE=* # not used
      - ZERO_AUTH_JWKS_URL=* # not used
      - ZERO_PUSH_URL=* # not used
      - BETTER_AUTH_URL=http://localhost:${APP_PORT:-54782}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - LIQUA_CONFIG_JSON=${LIQUA_CONFIG_JSON}
    depends_on:
      migrator:
        condition: service_completed_successfully
      zero:
        condition: service_started

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${APP_PORT:-54782}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_started
      zero:
        condition: service_started
      ollama:
        condition: service_started

volumes:
  postgres_data:
  zero_data:
  ollama_data:
