import "~/styles/globals.css";

import { ReactScan } from "~/components/react-scan";
import { type Metadata } from "next";
import { IBM_Plex_Mono, Poppins } from "next/font/google";

import { AlertEmitter } from "~/components/alert";
import { RenameDialog } from "~/components/rename-dialog";
import { Toaster } from "~/components/system/sonner";
import { env } from "~/env";
import { TRPCReactProvider } from "~/lib/trpc";
import { ZeroAuthenticatedProvider } from "~/zero/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-sans",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {env.NEXT_PUBLIC_ZERO_SERVER_URL.includes("localhost") && <ReactScan />}
      <body
        className={`${poppins.variable} ${ibmPlexMono.variable} font-sans`}
        translate="no"
      >
        <TRPCReactProvider>
          <ZeroAuthenticatedProvider>{children}</ZeroAuthenticatedProvider>
        </TRPCReactProvider>
        <Toaster />
        <AlertEmitter />
        <RenameDialog />
      </body>
    </html>
  );
}
